server:
  port: 8081


spring:
  application:
    name: service-authority-java
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:service-authority-java
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:jpa.database-platform: org.hibernate.dialect.H2Dialect